/* tslint:disable */
/* eslint-disable */
/**
 * AutoAtendimento.Host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Produto
 */
export interface Produto {
    /**
     * 
     * @type {number}
     * @memberof Produto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Produto
     */
    'nome'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Produto
     */
    'valor'?: number;
    /**
     * 
     * @type {string}
     * @memberof Produto
     */
    'codigoBarras'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Produto
     */
    'descricao'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Produto
     */
    'ativo'?: boolean;
}

